services:
  typescript:
    build:
      context: .
      target: dev
    working_dir: /home/nonroot/app
    tty: true
    volumes:
      - .:/home/nonroot/app
      - ./config/profile.conf:/home/nonroot/.aws/config
      - node_modules:/home/nonroot/app/node_modules

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - GATEWAY_LISTEN=0.0.0.0:4566
      - SERVICES=sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  node_modules: