name: buck3t

services:
  backend:
    build:
      context: .
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - gomodcache:/home/gopher/pkg/mod
    env_file:
      - .env
    entrypoint: [ "air" ]

volumes:
  gomodcache: