name: deployment

on:
  create:
    tags:
      - 'v*'

jobs:
  cd:
    name: cd
    runs-on: ubuntu-22.04

    steps:
      - name: Install so dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build
        run: make build-bundle

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit changes
        id: commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git HEAD:master

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ github.ref }}
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Build)
        id: upload_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/target/release/watchdog
          asset_name: watchdog-x86_64-unknown-linux-gnu
          asset_content_type: application/octet-stream; charset=utf-8