services:
  development:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
      - "3100:3100"
    tty: true
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    container_name: sguard_dev
  # magazord-tfk:
  #   image: "traefik:v2.6"
  #   command:
  #     - "--api.insecure=true"
  #     - "--log.level=debug"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "8000:8080"
  #   extra_hosts:
  #     - "host.docker.internal:${HOST_IP:-127.0.0.1}"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./config/traefik/static.yml:/etc/traefik/traefik.yml:ro
  #     - ./config/traefik/dynamic:/etc/traefik/dynamic:ro
  #     - ./config/ssl:/etc/certs:ro
  #   container_name: sguard_dev

volumes:
  node_modules: