http:
  services:
    sguard-api:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3100/
        passHostHeader: true

    sguard-web:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:3000/
        passHostHeader: true

  routers:
    sguard-api-http:
      entryPoints:
        - http
      service: sguard-api
      rule: HostRegexp(`api.oauth.local.com.br`)

    sguard-api-https:
      entryPoints:
        - https
      service: sguard-api
      rule: HostRegexp(`api.oauth.local.com.br`)
      tls: {}

    sguard-web-http:
      entryPoints:
        - http
      service: sguard-web
      rule: HostRegexp(`web.oauth.local.com.br`, `web.oauth.trunk.com.br`)

    sguard-web-https:
      entryPoints:
        - https
      service: sguard-web
      rule: HostRegexp(`web.oauth.local.com.br`, `web.oauth.trunk.com.br`)
      tls: {}

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/certs/sguard.pem"
        keyFile: "/etc/certs/sguard-key.pem"