external:
  provider:
    type: jira
    config:
      baseUrl: 
      username: 
      password: 
database:
  provider:
    type: postgres
    config:
      host: database      
      dbname: donatelo
      port: 5432
      username: postgres
      password: donatelo
      entities:
        - /home/nonroot/app/src/database/entities/*{ts,js}
        - /home/nonroot/app/dist/database/entities/*{ts,js}
      migrations:
        - /home/nonroot/app/src/database/migrations/*{ts,js}
        - /home/nonroot/app/dist/database/migrations/*{ts,js}